spring:
  redis:
    host: 47.98.178.84
    port: 6379
    database: 0
    password: password
    timeout: 60s  # 连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
#    lettuce:
#      pool:
#        # 最大空闲连接数
#        max-idle: 500
#        # 最小空闲连接数
#        min-idle: 50
#        # 等待可用连接的最大时间，负数为不限制
#        max-wait:  -1s
#        # 最大活跃连接数，负数为不限制
#        max-active: -1